language: cpp

before_install:
 - export NUM_CPU=3
 - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted" -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq libgoogle-glog-dev libatlas-base-dev libeigen3-dev
 

install:
 - cd ..

# install ceres
 - curl http://ceres-solver.org/ceres-solver-1.10.0.tar.gz | tar xvz
 - mkdir ceres-bin
 - cd ceres-bin
 - cmake ../ceres-solver-1.10.0
 - make -j$NUM_CPU
# - make test
 - sudo make install
 - cd ..

 - cd bundler_sfm


script:
 - make -j$NUM_CPU
 - sudo cp bin/libANN_char.so /usr/lib
