language: cpp

before_install:
 - export NUM_CPU=3
 - sudo apt-get install -qq libatlas-base-dev libeigen3-dev gfortran libgoogle-glog-dev libsuitesparse-dev
# libgflags-dev
 - ls -la /usr/include/eigen3
 - sudo ln -sf /usr/include/eigen3/Eigen /usr/include/Eigen


install:
 - cd ..

# install ceres
 - curl http://ceres-solver.org/ceres-solver-1.10.0.tar.gz | tar xvz
 - mkdir ceres-bin
 - cd ceres-bin
 - dpkg -L libeigen3-dev
 - cmake -D EIGEN_PATH=/usr/include/eigen3/Eigen ../ceres-solver-1.10.0
 - make -j$NUM_CPU
# - make test
 - sudo make install
 - cd ..

 - cd bundler_sfm


script:
 - make -j$NUM_CPU
 - sudo cp bin/libANN_char.so /usr/lib
